### ISSUE TITLE
kmake repository branch is names 'main' instead of 'master'

### ISSUE THREAD

**Issue by psiryan** [Kode/kmake_bin#1]
The repository default branch is titled `main` instead of `master`. This causes the documented command for updating the Kha submodule [git submodule foreach --recursive git pull origin master](http://kha.tech/download) repositories to fail for this submodule with the following error message:
```
Entering 'Kinc/Tools/kmake'
fatal: couldn't find remote ref master
fatal: run_command returned non-zero status for Kinc/Tools/kmake
.
fatal: run_command returned non-zero status while recursing in the nested submodules of Kinc
```

**Comment by RobDangerous** [comment]
That has not been the documented command for a long time (at least not on https://github.com/Kode/Kha/wiki/Getting-Started - is it still somewhere else?).
Nonetheless I've now switched everything to main.
